### ISSUE TITLE
Recommend Option be added to return the quaternions

### ISSUE THREAD

**Issue by mjs513** [arduino-libraries/MadgwickAHRS#10]
Besides YPR the quaternions are useful to calculate dynamic acceleration as well as other coordinate transformations.  I recommend a getQ function be added to the filter files.  In MadgwickAHRS.cpp you could add:

```
void Madgwick::getQ(float * q) {
    q[0] = q0;  
    q[1] = q1;
    q[2] = q2;
    q[3] = q3;
}
```

while in MadgwickAHRS.h under public functions:

`void getQ(float * q);`

In the visualizer sketch you would need to add:
`float q[4];`
and obviously to call the new function:
`filter.getQ(*q);`

R.
Mike

**Comment by PaulStoffregen** [comment]
Yes, will do.

**Comment by mjs513** [comment]
Thank you Paul, appreciate it.

**Comment by GMcDowellJr** [comment]
> 
> 
> Besides YPR the quaternions are useful to calculate dynamic acceleration as well as other coordinate transformations. I recommend a getQ function be added to the filter files. In MadgwickAHRS.cpp you could add:
> 
> ```
> void Madgwick::getQ(float * q) {
>     q[0] = q0;  
>     q[1] = q1;
>     q[2] = q2;
>     q[3] = q3;
> }
> ```
> 
> while in MadgwickAHRS.h under public functions:
> 
> `void getQ(float * q);`
> 
> In the visualizer sketch you would need to add:
> `float q[4];`
> and obviously to call the new function:
> `filter.getQ(*q);`
> 
> R.
> Mike

Looks like this was never implemented. Curious if there's something wrong with it as I'm struggling to implement it myself.
